### ISSUE TITLE
feature request: add `.env` files

### ISSUE THREAD

**Issue by ghostsquad** [pre-commit/identify#100]
This is a feature request to add `.env` files to identify

**Comment by asottile** [comment]
what should `.env` be classified as?

**Comment by ghostsquad** [comment]
`env` maybe? or `dotenv` ?

Here's some popular libraries/tools that use files like this:

https://github.com/motdotla/dotenv?ts=4

https://github.com/joho/godotenv?ts=4

https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

https://parceljs.org/env.html

**Comment by asottile** [comment]
sure, would you like to add it?  it's a little odd since usually you don't check in the `.env` file

I think this would go [here](https://github.com/chriskuehl/identify/blob/b8a3ad33b3b6e26da11b03d5f577f920710c2d18/identify/extensions.py#L184)?

**Comment by ghostsquad** [comment]
>  it's a little odd since usually you don't check in the .env file

that's actually not true. It's quite convenient to check in .env files that contain non-secret information for development & testing environments. In fact, most of the tools above support varying features for overriding values. Like in `godotenv` you apply .env files in order of most specific to least specific like:

```
local.env
development.env
global.env
```

and once a value is set, it is _not_ overwritten (which is why you do it in this order). But other tools do the opposite (so definitely read the docs! 📖 )

But anyways, if your application follows the 12-factor methodology: https://12factor.net/

Then likely it's simply easiest to define your config in this way.

**Comment by ghostsquad** [comment]
> I think this would go [here](https://github.com/chriskuehl/identify/blob/b8a3ad33b3b6e26da11b03d5f577f920710c2d18/identify/extensions.py#L184)?

Yes, likely. Any file ending in `.env` though, there's a small concern that existing projects may not use this convention, as I've seen `.env.test` and similar before.

also, apparently, I haven't entirely even read all the documentation here:
https://github.com/motdotla/dotenv?ts=4#should-i-have-multiple-env-files

Which suggests not use multiple, overriding env files. I'm not entirely sure I agree, but that's ok.

**Comment by asottile** [comment]
- https://github.com/motdotla/dotenv?ts=4#should-i-commit-my-env-file
- https://github.com/motdotla/dotenv?ts=4#should-i-have-multiple-env-files

both seem to suggest you should (1) not check it in and (2) not have cascading

**Comment by ghostsquad** [comment]
The only reason is says not to check them in, is because they may contain secrets.

**Comment by Cediddi** [comment]
Of course, you shouldn't publish your `.env` file to the git repo, but you may want to send an example one as `.example.env` or a SOPS encrypted template with predefined secrets (in case of development environment) `.enc.template.env`

Neither pre-commit nor this repo will solve projects that are not compliant with 12 Factors App methodology, but with env file type I can publish a hook to check if they are encrypted or not.

**Comment by Cediddi** [comment]
12 factors app is a great methodology, but that doesn't mean every project which deals with dotenv files has to follow it perfectly. But that doesn't change the fact that there's a dotenv file format that's being widely used, and it should be recognized by this library.

In my case, I'm writing a hook to check SOPS encrypted files, and one of the formats SOPS support is dotenv files (sharing pre-filled .example.env files for development environment setups is something I saw multiple times). Another case might be forbidding dotenv files to be committed via pre-commit hooks. And the last thing that comes to my mind is a linter for dotenv files, (https://github.com/dotenv-linter/dotenv-linter)

So there is indeed a dotenv file format, and there are legitimate use cases for those in the context of pre-commit hooks.

:pray:

**Comment by Cediddi** [comment]
I guess we can close this issue because 2.5.3 is published to pypi :) Thanks Anthony and Thanks Wes.
