### ISSUE TITLE
Support .in files (or just cmake.in)

### ISSUE THREAD

**Issue by henryiii** [pre-commit/identify#119]
A common pattern is a `.in` file, which should be identified as the inner type, that is, `MyConfig.cmake.in` should be a CMake file, and `pytest.ini.in` should be an `ini` file, etc. AFAICT, this is not currently supported?

**Comment by asottile** [comment]
the problem with `.in` is it usually implies some type of preprocessor, and almost always the preprocessor templating is incompatible with the end file format (you wouldn't lint a `foo.py.in` file the same as a `foo.py` files).   Additionally, `.in` could imply any sort of preprocessor (it may be autotools, it could be some simple `sed`, jinja, who really knows!)

As such, I don't think this should be implemented, what are your thoughts?

**Comment by henryiii** [comment]
In my case, I want to identify files for formatting, so I definitely want to pick up `cmake.in` files and format them too. However, for a linter, I'd like to be much pickier, you are right. Would it be possible to add a modifier for file types? Such that `X.in` is a X file with an `.in` extension?

**Comment by asottile** [comment]
at that point I would probably revert to using `types: [file]` and implementing what you need in the [`files:`](https://pre-commit.com/#config-files) regex

**Comment by henryiii** [comment]
CMake-format is [explicitly supporting `*.cmake.in` files in it's next release](https://github.com/cheshirekow/cmake_format/issues/109), so it would be very nice to be able to elegantly identify these (it actually caught me by surprise that they were not being picked up by default, since they are a very common file type in CMake).  (And an explicit regex is what I'm currently doing)

**Comment by henryiii** [comment]
By the way, `.cmake.in`'s might be a bit special here, since they are a very common CMake file type (pretty much every package has a `*Config.cmake.in`) and very well defined, with just one additional bit of syntax. Unlike most other cases, I'd even expect the pre-commit extension for cmake-format to find `cmake.in` files by default, actually. But I would think a general solution here would be better, as it would give the ability to easily identify other `.in` types, but I mostly care about `cmake.in` at the moment.

**Comment by henryiii** [comment]
You are right! I was using 0.6.10 since that was the last version out for pre-commit, but now that I've updated to 0.6.11 (thanks for releasing that), this works!
