### ISSUE TITLE
Add support for .myst (Markedly Structured Text) extension

### ISSUE THREAD

**Issue by Skylion007** [pre-commit/identify#162]
Currently, we are working on a pre-commit hook for JuPyText, but noticed the .myst extension doesn't appear in the list of supported extensions. This should be added so that we can properly use the types field for the pre-commit hook instead of relying on complex regex.

https://myst-parser.readthedocs.io/en/latest/

**Comment by asottile** [comment]
send a patch!

**Comment by Skylion007** [comment]
@asottile Done.
