### ISSUE TITLE
Add .d and .vala as filetypes

### ISSUE THREAD

**Issue by pocc** [pre-commit/identify#258]
Both D and vala are languagse and have `.vala` and `.d` filetypes respectively. They are text files.

**Comment by asottile** [comment]
please send a PR with references -- thanks!

**Comment by ngie-eign** [comment]
@asottile : this issue is still referenced in https://github.com/pocc/pre-commit-hooks/blob/336fdd7c3cab698ead0b1c95157b9e74d3906b62/.pre-commit-hooks.yaml#L28 and I didn't see a linked PR or commit, so I opened https://github.com/pre-commit/identify/pull/549 to address the ask by @pocc .
