### ISSUE TITLE
Upgrade to 2.4.1 causes error whilst using "coverage report" command

### ISSUE THREAD

**Issue by szerepak** [pre-commit/identify#262]
After upgrading from `identify` `2.4.0` to `2.4.1` I'm getting the following error message:
```
# coverage report -m --skip-covered
No source for code: '/app/rep-10>'
```

with 2.4.0 works fine.

Since it's a patch version, I thought it's useful to raise it, as it's not backwards compatible anymore (at least for me).

**Comment by asottile** [comment]
do you have a reproduction? there's almost zero chance it's identify

**Comment by szerepak** [comment]
I'm not sure, what do you mean by the _reproduction_?

What, I've done is:

1. Run `poetry update`
2. Out of several packages, `poetry` updated `identify`
3. Run `coverage run --source . -m py.test -c $PYTEST_CONFIG --verbose --junitxml=report.xml --html=htmltest/report.html --self-contained-html`
4. Pytest run as expected
5. Run `coverage report -m --skip-covered`
6. Got `No source for code: '/app/rep-10>'`
7. Debug
8. The only package I've downgraded was `identify` from `2.4.1` -> `2.4.0`
9. Re-run of `coverage report` worked as expected

Maybe the `identify`'s dependency then.

**Comment by asottile** [comment]
a reproduction is something I can run on my computer to see your problem, since I don't have access to your computer and can't see your screen I can't help you
