### ISSUE TITLE
Add option to dump all supported tags

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/identify#265]
It seems that identify does not have an option for dumping all supported tags that can be reported by the library.

This is a problem as it blocks resolution of one of the problems you reported on https://github.com/SchemaStore/schemastore/pull/1970#issuecomment-998961856 -- where `types: [...]` does not check for valid strings. Without having identify report which tags/types it can return, it makes little sense to manually dig the source code to build such a list.

I had a brief look ar the source code and it seems that there are 3-4 places where these could be gathered from.

What do you think about a `identify-cli --list` option?

**Comment by asottile** [comment]
https://github.com/pre-commit/identify/blob/43af0b92675a30b7f128a40efba6a120bd8f3327/identify/identify.py#L39

**Comment by ssbarnea** [comment]
Thanks!
```
from identify.identify import ALL_TAGS
print(ALL_TAGS)
```
