### ISSUE TITLE
Feature request: Please consider reopening #189 or a similar change for allowing executable checking to work in more diverse contexts

### ISSUE THREAD

**Issue by posita** [pre-commit/identify#289]
I understand the sentiment not to want to build in bug fixes for other entities' software, but I would like to make an appeal to reopen and merge #189, originally authored by @geeky-smurf. In the alternative, I want to request considering a new PR in its place with a slightly different approach.

### Two different, but overlapping permission checks is not inconsistent with `pre-commit`.

@geeky-smurf's approach was quite elegant in that it does very nearly what the existing code does in [precisely the same place](https://github.com/pre-commit/identify/pull/189/files#diff-b9080a0760516c25fb95bfd4b1992f963514b6d72c3febf92869c0500c41977d). It's _**almost**_ just as readable. There's no "if running in Docker" or "if running on MacOS" nonsense. It's using proximal primitives in an intended way.

It's understandable you wouldn't want to lose or replace the `os.access(path, os.X_OK)` check. In that case, there's a tweak worth considering:

``` python
executable = os.access(path, os.X_OK) or \
    os.stat(path).st_mode & stat.S_IXUSR  # no need to check group or other bits
```

That would allow the nuances of [`os.access`](https://docs.python.org/3/library/os.html#os.access) to persist, but fall back to looking for executable permissions in @geeky-smurf's alternate way. Again, it's _**almost**_ just as readable. Any impact to maintainability should be slight, if not negligible.

### `pre-commit` is _**already**_ using a proxy for the intended source of truth: the Git index.

`pre-commit` is looking to the filesystem as a proxy to checking whether Git thinks the files are executable. Strictly speaking, it's already compromising on that front. What it's _**really**_ after is something like `git ls-files --stage <path> …`. _**Most**_ of the time, the filesystem permissions are in concert with this value, but not always. Git is the source of truth. Expanding `os.access(…)` to inclusively check `os.stat(…).st_mode` gets closer to that on more systems than either standing alone.

### The corresponding Docker issue is not easily dismissible as a bug. It's a deliberate tradeoff, and it implicates the ability to run `pre-commit` in architectures beyond Docker.

@djs55 has a decent write up [here](https://github.com/docker/for-mac/issues/5509#issuecomment-930330856). The short version is that, when running on OS X, Docker affords access to the host filesystem using FUSE as an intermediary, which also makes tradeoffs of complete executable permission detection and performance.

Docker is probably the most popular place this comes up, but it _**could**_ come up elsewhere. The likelihood of encountering another case only increases as `pre-commit` gains popularity.

### Being flexible on ferreting out the executable status improves usability without compromising correctness, which only serves `pre-commit` and its users.

To my knowledge, doing a `os.access(…) or os.stat(…).st_mode & …` is not over broad. In other words, I don't think the change will all of a sudden start identifying non-executable files as executable. Assuming that's correct, then such a change doesn't lead to correctness issues that take away from `pre-commit`'s value. However, by adding the change, `pre-commit` becomes a smidge more flexible on systems where this problem might occur, which is of value to a greater audience of users.

### If #189 does not appeal to you, please consider my proposed alternative.

If you are amenable, I am happy to cut a PR. Thank you very much for your time and consideration.

**Comment by posita** [comment]
@asottile, I understand you don't want to accept this, but can you offer some insight as to why?

**Comment by asottile** [comment]
there's several duplicates which answer that -- please search the issue tracker next time
