### ISSUE TITLE
Aliasing system?

### ISSUE THREAD

**Issue by asottile** [pre-commit/identify#29]
I frequently forget whether it is `javascript` or `js` (or various others) -- perhaps we should have an aliasing system?

**Comment by michaelfromyeg** [comment]
Is this ticket in progress? Perhaps it's worth re-visiting #155 as the simple solution, since (afaict from the issues) this doesn't seem to be a widespread problem.

If aliasing is a must-do, could I pick this up?

**Comment by asottile** [comment]
I'm declining this

**Comment by asottile** [comment]
6 years and clearly yagni. it doesn't pass silently so at most it's a cosmetic annoyance
