### ISSUE TITLE
Feature request: add & distribute py.typed marker file

### ISSUE THREAD

**Issue by aneeshusa** [pre-commit/identify#295]
Hello!

I'm using this library in my codebase and I noticed that this repo already has type annotations and is running mypy in CI. Could a py.typed file be added to the repo and included in `package_data` (per https://peps.python.org/pep-0561/) so mypy is able to transitively type check my codebase against the type annotations in this repo?

I also kicked off the process internally at $WORK to get approval to contribute to this repository. If you are open to this feature request, I am happy to send a PR myself if you don't have time to implement this.

**Comment by asottile** [comment]
there is no public python api, depend on the internals at your own risk

**Comment by asottile** [comment]
woops wrong repo
