### ISSUE TITLE
Identify protobuf generated files

### ISSUE THREAD

**Issue by devbharat** [pre-commit/identify#320]
Files with extensions *.pb.cc and *.pb.h for cpp generated code.

**Comment by asottile** [comment]
those will be identified as c++ already

**Comment by devbharat** [comment]
@asottile could they be identified as another sub-category as well? For example, as proto-generated-c++? The issue is not all pre-commit hooks agree with the formatting (most common being trailing-whitespace) of these files and want to reformat them. Currently we use regex to ignore these files, but using identify tags would be better.

**Comment by asottile** [comment]
that would need to be an entirely new concept to identify -- of which you already have a perfectly workable solution for

though I'd argue that you shouldn't be checking in generated files -- though that's probably a you-problem rather than a identify-should-change problem
