### ISSUE TITLE
Subtags for subextensions

### ISSUE THREAD

**Issue by CSymes** [pre-commit/identify#332]
Is there a way to classify subextensions to use additional tags to the actual extension?
Say you have file `example.x.y`, and while `identify` recognises extension `.y`, the `.x.y` denotes additional information that would be beneficial to have access to.
For instance, in the C# domain, [several IDE tools](https://stackoverflow.com/a/10103366/1543908) generate `.designer.cs` files and it would be useful to tag these as (e.g.) `autogenerated` in addition to the standard C# tags.

Is this level of tagging too granular for this tool?
Is this level of pattern matching currently supported?

**Comment by asottile** [comment]
there isn't -- more information in #125 / #119
