### ISSUE TITLE
Non-executable shell script should be detected as "shell"

### ISSUE THREAD

**Issue by l0b0** [pre-commit/identify#350]
Actual behaviour:

```console
$ lorri init
[…]
$ identify-cli .envrc 
["file", "non-executable", "text"]
$ chmod u+x .envrc
$ identify-cli .envrc 
["bash", "executable", "file", "shell", "text"]
```

Expected behaviour: the results should be identical for the executable and non-executable versions of the file, because the first line in the file is a valid shell script shebang line: `#!/usr/bin/env bash`.

**Comment by asottile** [comment]
[the README is short and addresses this](https://github.com/pre-commit/identify#with-a-file-on-disk)

**Comment by asottile** [comment]
nope, this is a "you stopped reading before you got to the relevant part" problem:

> If executable, the shebang is read and the interpreter interpreted

**Comment by l0b0** [comment]
OK, so it's not working as expected. Why does it not read the shebang line of non-executables?

**Comment by l0b0** [comment]
Tools like IDEs and ShellCheck do read the shebang line of non-executables, after all.

**Comment by asottile** [comment]
the point of a shebang is to indicate to the OS how to execute it -- it is only relevant when it is executable

parsing shebangs of non-executables would also mean everything has to read every file always which is slow

this is not up for debate so please do not waste your time and my time
