### ISSUE TITLE
Question: identify path.sh file but with #!/usr/bin/env bash shebang

### ISSUE THREAD

**Issue by imomaliev** [pre-commit/identify#356]
Often `.sh` files have `#!/usr/bin/env bash` shebang, but identify does not recognize them as `bash` files.
## Steps to reproduce
```console
$ echo '#!/usr/bin/env bash' > t.sh
$ chmod +x t.sh
$ identify-cli t.sh
["executable", "file", "shell", "text"]
```
I am not sure if this should be considered a bug, I couldn't find any mentions about this in this repo. But I see that this is intended behavior https://github.com/pre-commit/identify/blob/8457cd7f75be6aec028da6d68d5b5213dfd4a69e/identify/identify.py#L65L69

So my question is, may be we should add special case when shebang takes priority over file extension for such files?

**Comment by asottile** [comment]
please search the issue tracker, there are several duplicates

**Comment by imomaliev** [comment]
@asottile I am sorry to be taking your time, but the only similar issue that I could find is https://github.com/pre-commit/identify/issues/350. But it does not address my question, because it asks about "non-executable" shell script. Could you please point me to the issues you are referring to?

**Comment by asottile** [comment]
if a file has a known extension it's contents are never read because that is slow

**Comment by imomaliev** [comment]
Ah, yeah... You mentioned it here https://github.com/pre-commit/identify/issues/350#issuecomment-1340083742. For some reason I assumed it doesn't apply to my question, sorry. Thank you for your patience. Happy holidays!
