### ISSUE TITLE
detect custom shebang as Python

### ISSUE THREAD

**Issue by spaceone** [pre-commit/identify#366]
We have executable files without file extensions with the shebang `#!/usr/share/test/runner python3` and would like them to be detected by `pre-commit` as Python files.

The `file` command detects them as `Python script, ASCII text executable`.
`identify-cli` detects them as `["executable", "file", "text"]`

We need e.g. a configuration of valid Python shebang strings.

**Comment by asottile** [comment]
identify implements a _convention_ -- if you do weird things it can't really help you
