### ISSUE TITLE
Apple keynote files are incorrectly identified as text files

### ISSUE THREAD

**Issue by aharrison24** [pre-commit/identify#391]
On an Apple keynote file I get:

```shell
> identify-cli my_presentation.key
["file", "non-executable", "pem", "text"]
```

Is it possible for 'identify' to check for binary content and label keynote files as "binary"?

**Comment by asottile** [comment]
unfortunately nothing can be done about this -- the extension is ambiguous and a more popular format was chosen

**Comment by aharrison24** [comment]
OK thank you. Would you look favorably on a PR to introduce a local configuration file for identify, that lets users provide custom overrides for some file types? Or is that out of scope for the project?

**Comment by asottile** [comment]
assuming you're using this through `pre-commit` you can already override `types` / `files` to get what you want
