### ISSUE TITLE
With identify 1.6.2 ps1 files no longer correct recognized

### ISSUE THREAD

**Issue by rbroderi** [pre-commit/identify#454]
See commit 31b2ced where support was added.
Currently when running identity-cli I now get:
```
["Executable", "file", "text"] and not .... "PowerShell"]

**Comment by asottile** [comment]
show the command you ran and the output?

**Comment by asottile** [comment]
that output you've written is impossible fwiw so I suspect pebkac

**Comment by rbroderi** [comment]
Yup sorry looks like pip-review "updated" identify from 2.5.35 to 1.6.2. reinstalled version 2.5.35 and it now works. I am guessing that it was not introduced until after 1.6.2. sorry about that. Thanks for the quick reply!
