### ISSUE TITLE
Additional heuristics for jinja files

### ISSUE THREAD

**Issue by choman** [pre-commit/identify#465]
I have a bash script that ends with ".sh.j2"

This is the result of identify-cli against a bash script and a bash script template:
```
["executable", "file", "shell", "text"]
["executable", "file", "jinja", "text"]
```

It would be better, IMHO, if the output was more like 
```
["executable", "file", "shell", "text"]
["executable", "file", "shell", "jinja", "text"]
```

Also note that the magic cookie in these scripts is indeed /bin/bash, but bash is not in the tags because the extension is just ".sh"

Note that on linux, the file program correctly identifies the .sh.j2
```
file templates/staging/load.sh.j2 
templates/staging/load.sh.j2: Bourne-Again shell script, Unicode text, UTF-8 text executable


```

**Comment by asottile** [comment]
no it would not, a .sh.j2 file is not going to be valid shell syntax
