### ISSUE TITLE
Recognize OpenSCAD files

### ISSUE THREAD

**Issue by EmperorArthur** [pre-commit/identify#482]
Please add support for recognizing OpenSCAD files.

* .scad
* .csg

".csg" files are a subset of OpenSCAD, so an additional tag would be appreciated for them.

**Comment by asottile** [comment]
please send a pr, but please make sure to research if it is unambiguous first.  we tend not to operate as a "do work for me plz" service

**Comment by EmperorArthur** [comment]
Sure, but why are #445 and #437 open, but this one closed?

Most projects either prefer to have issues associated with PRs, and/or to use issues as a backlog when time permits.  This project not wanting that when there have been similar requests open for almost a year is confusing.

You might want to set up Github so there's a popup / template when we create new issues.  Plus close #445, and #437.  Otherwise, people will be confused at best and insulted at worst.

**Comment by EmperorArthur** [comment]
@asottile I don't know what you want on some of these repos.

I tried to create a PR for https://github.com/pre-commit/action to add a warning that setup-python must be at v3, but you've disabled both creating PRs and Issues there. It's very frustrating.

**Comment by asottile** [comment]
> Sure, but why are https://github.com/pre-commit/identify/issues/445 and https://github.com/pre-commit/identify/issues/437 open, but this one closed?

good point -- close those too

**Comment by asottile** [comment]
> I tried to create a PR for https://github.com/pre-commit/action to add a warning that setup-python must be at v3, but you've disabled both creating PRs and Issues there. It's very frustrating.

I put temporary moderation limits because people were spamming the repo with duplicate issues repeatedly and not doing any sort of basic investigation or research into their actual problems.

**Comment by asottile** [comment]
I suspect also your PR would have fallen into that category as well -- it does not need to be v3 and I've been using it just fine with the latest setup-python.  so in a way the moderation limits are doing their job

**Comment by EmperorArthur** [comment]
> it does not need to be v3 and I've been using it just fine with the latest setup-python

I just tired changing v3 to v5, and it failed...

**Comment by asottile** [comment]
then you did it wrong
