### ISSUE TITLE
Bug: Dockerfile.dockerignore is identified as dockerfile instead of dockerignore

### ISSUE THREAD

**Issue by thiagowfx** [pre-commit/identify#489]
## Observed

Currently (as of HEAD), a `Dockerfile.dockerignore` file is tagged with `{'dockerfile', 'text'}`.

## Expectation

It should be tagged with `{'dockerignore', 'text'}`.

## Reference

https://docs.docker.com/build/concepts/context/#syntax

This pattern is common: https://sourcegraph.com/search?q=context:global+Dockerfile.dockerignore (I don't really know why, `.dockerignore` should be enough).

Why is this an issue? When using pre-commit hooks that expect to act on Dockerfiles, they fail when parsing `Dockerfile.dockerignore` files.

Obviously, when using pre-commit, one could work around that by adding `exclude: Dockerfile.dockerignore`.

The following tests could be added:

```
% git diff
diff --git tests/identify_test.py tests/identify_test.py
index c0e5410..7eea3e2 100644
--- tests/identify_test.py
+++ tests/identify_test.py
@@ -158,6 +158,8 @@ def test_tags_from_path_plist_text(tmpdir):
         ('Containerfile', {'text', 'dockerfile'}),
         ('Dockerfile', {'text', 'dockerfile'}),
         ('Dockerfile.xenial', {'text', 'dockerfile'}),
+        ('.dockerignore', {'text', 'dockerignore'}),
+        ('Dockerfile.dockerignore', {'text', 'dockerignore'}),
         ('xenial.Dockerfile', {'text', 'dockerfile'}),
         ('Pipfile', {'text', 'toml'}),
         ('Pipfile.lock', {'text', 'json'}),
```

I considered sending a pull request however I can't think of an elegant way to do so other than hard-coding this case in https://github.com/pre-commit/identify/blob/f075954372758b34ef542c2e895000ea660a47c9/identify/identify.py#L92-L96.

**Comment by asottile** [comment]
this is expected.  conventional names are always matched first.

arguably that filename is ambiguous and should be changed (or you can leverage `exclude` if needed)
