### ISSUE TITLE
Does not identify files using /bin/env in shebang line

### ISSUE THREAD

**Issue by psa** [pre-commit/identify#495]
identify fails to properly identify files which use `#!/bin/env` instead of `#!/usr/bin/env`:

For example:

* `#!/usr/bin/env python`:
```
identify-cli usr-bin-env-python-test
["executable", "file", "python", "text"]
```

* `#!/bin/env python`:
```
identify-cli bin-env-python-test
["executable", "file", "text"]
```

**Comment by asottile** [comment]
correct. it only supports the conventional `/usr/bin/env`
