### ISSUE TITLE
.pyi files should be identified as python

### ISSUE THREAD

**Issue by chadrik** [pre-commit/identify#51]
.pyi files are the basis for [PEP 484 static type checking](https://www.python.org/dev/peps/pep-0484/), and should be identified as python files.

**Comment by asottile** [comment]
I'm hesitant to classify them directly as python as they have quite different formatting style (for instance I wouldn't run flake8 on them). That said, they aren't classified at all yet. Would you be OK with them (for now) being classified as `pyi` and then perhaps in the future extend that to python?

**Comment by chadrik** [comment]
Wow, thanks for the fast response.

I'm working on adding stubs to [attrs](https://github.com/python-attrs/attrs), which uses [pre-commit](https://pre-commit.com/) to run [black](https://github.com/ambv/black/issues/new) to reformat python files, but `pre-commit` will only feed files to `black` which `identify` marks as python (whew!  still with me?).

> I'm hesitant to classify them directly as python as they have quite different formatting style (for instance I wouldn't run flake8 on them).

`black` for one is smart enough to treat `pyi` files specially when reformatting them, but I understand your wariness.

> Would you be OK with them (for now) being classified as pyi and then perhaps in the future extend that to python?

I have a solution that works for now, but I wanted to notify the authors of the various projects so that a better solution can be worked out.  I'm going to go point this out over at `black` and let you all sort it out ;)

**Comment by asottile** [comment]
for pre-commit (once `identify` supports `pyi`) you can hook it up as follows:

```yaml
    hooks:
    -   id: black
    -   id: black
         name: black (pyi)
         types: [pyi]
```

let me get `pyi`s classified for ya though :)

**Comment by asottile** [comment]
here's the PR to classify `pyi` as... well... `pyi` for now :) #52

**Comment by asottile** [comment]
pyi is now classified as of v1.1.3

**Comment by chadrik** [comment]
thanks!
